name: List Changed Files

on:
    push:
        branches:
            - main

jobs:
    list-changed-files:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Get added and modified .sql files
              id: changed-files
              run: |
                  git diff --diff-filter=AM --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '\.sql$' > changed_files.txt
                  cat changed_files.txt

            - name: Output added and modified .sql files
              run: |
                  echo "Added and modified .sql files:"
                  cat changed_files.txt

            - name: Upload changed .sql files as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: changed-files
                  path: changed_files.txt
