name: List Changed Files

on:
    push:
        branches:
            - main

jobs:
    list-changed-files:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Get added and modified files
              id: changed-files
              run: |
                  git diff --diff-filter=AM --name-only ${{ github.event.before }} ${{ github.event.after }} > changed_files.txt || true
                  cat changed_files.txt

            - name: Output added and modified files
              run: |
                  echo "Added and modified files:"
                  cat changed_files.txt

            - name: Run Python script with changed files
              run: |
                  python your_script.py changed_files.txt

            - name: Upload changed files as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: changed-files
                  path: changed_files.txt

            - name: Output processed files
              run: |
                  echo "Processed files:"
                  cat processed_files.txt

            - name: Upload processed files as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: processed-files
                  path: processed_files.txt
